import { useMemo, useState } from "react";
import { Building2, CheckCircle2, LockKeyhole, Target, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { challengesByModule, businessChallenges } from "@/data/challengesCatalog";
import { getCompletedCount, readProgress } from "@/data/progress";

const completedKey = "ia-academy-business-challenges";
const readCompleted = (): string[] => { try { return JSON.parse(localStorage.getItem(completedKey) || "[]"); } catch { return []; } };

export default function Challenges() {
  const progress = useMemo(() => readProgress(), []);
  const [completed, setCompleted] = useState(readCompleted);
  const [selectedId, setSelectedId] = useState(businessChallenges[0]?.id);
  const selected = businessChallenges.find(challenge => challenge.id === selectedId) ?? businessChallenges[0];
  const finish = () => { if (!selected || completed.includes(selected.id)) return; const next = [...completed, selected.id]; setCompleted(next); localStorage.setItem(completedKey, JSON.stringify(next)); };
  if (!selected) return null;

  return <main className="futurist-grid min-h-screen py-10"><div className="container space-y-8">
    <header className="max-w-3xl space-y-4"><p className="futurist-kicker">Laboratório profissional</p><h1 className="text-4xl font-black uppercase tracking-[-0.05em]">Aprenda trabalhando em problemas reais</h1><p className="text-lg leading-8 text-muted-foreground">Cada módulo desbloqueia um desafio de uma empresa fictícia. Você recebe contexto, restrições e critérios de aceite, define uma solução e apresenta evidências como faria em um time de produto ou dados.</p><div className="grid gap-3 sm:grid-cols-3"><div className="futurist-panel p-4"><Building2 className="mb-3 size-5 text-cyan-300" /><strong className="block text-2xl">{businessChallenges.length}</strong><span className="text-xs text-muted-foreground">cenários guiados</span></div><div className="futurist-panel p-4"><Target className="mb-3 size-5 text-lime-300" /><strong className="block text-2xl">{completed.length}</strong><span className="text-xs text-muted-foreground">desafios concluídos</span></div><div className="futurist-panel p-4"><Wrench className="mb-3 size-5 text-violet-300" /><strong className="block text-2xl">Entrega</strong><span className="text-xs text-muted-foreground">com evidência prática</span></div></div></header>
    <div className="grid gap-6 lg:grid-cols-[330px_1fr]">
      <aside className="futurist-panel h-fit overflow-hidden"><div className="border-b border-primary/20 bg-primary/5 p-4"><h2 className="font-semibold">Desafios por módulo</h2><p className="mt-1 text-xs text-muted-foreground">Conclua as aulas necessárias para desbloquear.</p></div><div className="divide-y divide-border">{businessChallenges.map(challenge => { const lessons = getCompletedCount(progress, challenge.moduleId); const unlocked = lessons >= challenge.unlockAfterLessons; const done = completed.includes(challenge.id); return <button type="button" key={challenge.id} onClick={() => unlocked && setSelectedId(challenge.id)} disabled={!unlocked} className={`w-full p-4 text-left transition-colors ${selected.id === challenge.id ? "bg-primary/10" : "hover:bg-primary/5"} ${!unlocked ? "cursor-not-allowed opacity-60" : ""}`}><div className="flex items-start gap-3">{done ? <CheckCircle2 className="mt-0.5 size-4 shrink-0 text-lime-300" /> : unlocked ? <Target className="mt-0.5 size-4 shrink-0 text-cyan-300" /> : <LockKeyhole className="mt-0.5 size-4 shrink-0 text-muted-foreground" />}<span className="min-w-0"><strong className="block truncate text-sm">{challenge.moduleLabel}</strong><span className="mt-1 block text-xs text-muted-foreground">{unlocked ? challenge.title : `Desbloqueia em ${challenge.unlockAfterLessons} aulas (${lessons}/${challenge.unlockAfterLessons})`}</span></span></div></button>; })}</div></aside>
      <section className="futurist-panel space-y-6 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="futurist-kicker">Briefing confidencial · {selected.industry}</p><h2 className="mt-2 text-3xl font-bold">{selected.title}</h2><p className="mt-2 text-muted-foreground">{selected.company} · {selected.difficulty} · {selected.stack.join(" · ")}</p></div>{completed.includes(selected.id) && <span className="inline-flex items-center gap-2 rounded-full border border-lime-400/30 bg-lime-400/10 px-3 py-1.5 text-xs text-lime-200"><CheckCircle2 className="size-4" /> Concluído</span>}</div><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-border bg-card p-4"><h3 className="mb-2 font-semibold text-cyan-200">Contexto da empresa</h3><p className="text-sm leading-6 text-muted-foreground">{selected.scenario}</p></div><div className="rounded-xl border border-border bg-card p-4"><h3 className="mb-2 font-semibold text-amber-200">Problema a resolver</h3><p className="text-sm leading-6 text-muted-foreground">{selected.problem}</p></div></div><div className="rounded-xl border border-primary/25 bg-primary/5 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Missão</p><p className="mt-2 text-lg leading-7 text-foreground">{selected.objective}</p></div><div><h3 className="mb-3 text-xl font-semibold">Roteiro de execução</h3><div className="grid gap-3 md:grid-cols-3">{selected.steps.map((step, index) => <article key={step.title} className="rounded-xl border border-border bg-card p-4"><span className="text-xs font-bold text-primary">0{index + 1}</span><h4 className="mt-2 font-semibold">{step.title}</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{step.brief}</p><p className="mt-3 text-xs text-cyan-200">Entrega: {step.deliverable}</p></article>)}</div></div><div><h3 className="mb-3 text-xl font-semibold">Critérios de aceite</h3><ul className="grid gap-2 md:grid-cols-3">{selected.acceptanceCriteria.map(criteria => <li key={criteria} className="rounded-lg border border-border bg-card p-3 text-sm text-muted-foreground">{criteria}</li>)}</ul></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5"><p className="max-w-xl text-xs leading-5 text-muted-foreground">Este é um ambiente simulado: use dados sintéticos, documente suas decisões e nunca inclua informações confidenciais de pessoas ou empresas reais.</p><Button type="button" onClick={finish} disabled={completed.includes(selected.id)} className="gap-2 bg-primary text-primary-foreground">{completed.includes(selected.id) ? <><CheckCircle2 className="size-4" /> Desafio concluído</> : "Marcar missão como concluída"}</Button></div></section>
    </div>
  </div></main>;
}
